"""BrightHR employee id <-> InVentry staff id mapping.

The two systems do not share identifiers, so the sync needs a lookup table.
It lives in employee_map.json (built by tools/build_employee_map.py) and is
deliberately explicit: an id we cannot translate is reported, never guessed.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Mapping, Optional

log = logging.getLogger(__name__)


class EmployeeMapError(RuntimeError):
    """The employee map is missing or malformed."""


@dataclass
class EmployeeMap:
    """Two-way mapping between BrightHR employee ids and InVentry staff ids."""

    brighthr_to_inventry: Dict[str, str] = field(default_factory=dict)
    names: Dict[str, str] = field(default_factory=dict)
    # When True an unmapped BrightHR id is used as-is as the InVentry staff id.
    # Only enable this once both systems are confirmed to share identifiers.
    fallback_to_brighthr_id: bool = False

    @property
    def inventry_to_brighthr(self) -> Dict[str, str]:
        return {v: k for k, v in self.brighthr_to_inventry.items()}

    @classmethod
    def load(cls, path: Path, required: bool = False) -> "EmployeeMap":
        map_path = Path(path)
        if not map_path.is_file():
            if required:
                raise EmployeeMapError(
                    f"Employee map not found at {map_path}. Build one with "
                    "`python tools/build_employee_map.py --help`."
                )
            log.warning(
                "No employee map at %s - BrightHR ids will be treated as unmapped. "
                "Nobody will be signed in until a map exists.",
                map_path,
            )
            return cls()
        try:
            raw = json.loads(map_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise EmployeeMapError(f"Employee map at {map_path} is not valid JSON: {exc}") from exc
        return cls.from_dict(raw)

    @classmethod
    def from_dict(cls, raw: Mapping[str, object]) -> "EmployeeMap":
        mappings = raw.get("mappings", {})
        if not isinstance(mappings, Mapping):
            raise EmployeeMapError("Employee map 'mappings' must be an object.")

        brighthr_to_inventry: Dict[str, str] = {}
        names: Dict[str, str] = {}
        for brighthr_id, value in mappings.items():
            key = str(brighthr_id).strip()
            if not key:
                continue
            # Accept either "EMP001": "SDI-114" or the richer object form.
            if isinstance(value, Mapping):
                staff_id = value.get("inventry_staff_id") or value.get("staff_id")
                name = value.get("name") or value.get("employee_name")
                if name:
                    names[key] = str(name).strip()
            else:
                staff_id = value
            if staff_id is None or str(staff_id).strip() == "":
                log.warning("Employee map entry %s has no InVentry staff id; skipping", key)
                continue
            brighthr_to_inventry[key] = str(staff_id).strip()

        duplicates = _find_duplicates(brighthr_to_inventry)
        if duplicates:
            raise EmployeeMapError(
                "Employee map has InVentry staff ids used by more than one BrightHR id: "
                + ", ".join(sorted(duplicates))
            )

        return cls(
            brighthr_to_inventry=brighthr_to_inventry,
            names=names,
            fallback_to_brighthr_id=bool(raw.get("fallback_to_brighthr_id", False)),
        )

    def to_dict(self) -> Dict[str, object]:
        return {
            "_comment": (
                "Maps BrightHR employee_id -> InVentry StaffID. Generated by "
                "tools/build_employee_map.py; review before use."
            ),
            "fallback_to_brighthr_id": self.fallback_to_brighthr_id,
            "mappings": {
                brighthr_id: {
                    "inventry_staff_id": staff_id,
                    "name": self.names.get(brighthr_id, ""),
                }
                for brighthr_id, staff_id in sorted(self.brighthr_to_inventry.items())
            },
        }

    def to_inventry(self, brighthr_id: str) -> Optional[str]:
        staff_id = self.brighthr_to_inventry.get(str(brighthr_id).strip())
        if staff_id:
            return staff_id
        if self.fallback_to_brighthr_id:
            return str(brighthr_id).strip()
        return None

    def to_brighthr(self, inventry_staff_id: str) -> Optional[str]:
        staff_id = str(inventry_staff_id).strip()
        brighthr_id = self.inventry_to_brighthr.get(staff_id)
        if brighthr_id:
            return brighthr_id
        if self.fallback_to_brighthr_id:
            return staff_id
        return None

    def name_for(self, brighthr_id: str) -> str:
        return self.names.get(str(brighthr_id).strip(), "")

    def __len__(self) -> int:
        return len(self.brighthr_to_inventry)


def _find_duplicates(mapping: Mapping[str, str]) -> set:
    seen: Dict[str, str] = {}
    duplicates = set()
    for brighthr_id, staff_id in mapping.items():
        if staff_id in seen:
            duplicates.add(staff_id)
        seen[staff_id] = brighthr_id
    return duplicates
